### ISSUE TITLE
User membership form page error

### ISSUE THREAD

**Issue by GDSimpson3** [ubports/docs.ubports.com#560] opened 2023-03-27 18:01 UTC
https://ubports.com/join-us

when you select your date of birth you get the error coming and it resets the date back to 3/27/23 (today in American date format)

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/103830594/228026767-254ef8d8-1ca2-431b-aafa-faa8ac7914eb.png">

**Comment by GDSimpson3** [comment] 2023-03-27 18:04
Perhaps if the code is in js/ts i can do something about it

**Comment by RayCulp** [comment] 2023-05-03 20:58
When I tested this earlier today, I got the same error message as you. Now it seems to be okay. The field is still automatically populated with the current date in US format, but I no longer see an error. Can you recheck and confirm? Also, I'm pretty sure the right place to open an issue about the main website would be here: https://github.com/ubports/ubports.com

**Comment by doniks** [comment] 2023-05-04 10:41
Hi @RayCulp or @GDSimpson3  , could you do me a favor and recreate this issue here: https://github.com/ubports/ubports.com/issues Now it is raised against "docs.ubports.com" but that's not where the issue is and so it's more cumbersome to get attention from the right people. I tried to transfer it just now, but I couldn't figure out how to do it, so maybe it's easiest if you could recreate it?

**Comment by RayCulp** [comment] 2023-05-13 21:10
> Now it is raised against "docs.ubports.com" but that's not where the issue is

That's true and I actually wanted to open a new issue in https://github.com/ubports/ubports.com/issues, but I hit an obstacle because the error appears to be gone now, i.e. I cannot reproduce it. If @GDSimpson3 can still reproduce the error, then he or I can create a new issue. If not, I would suggest simply closing this issue here. :-)

**Closed** 2023-05-15 06:03 UTC

**Comment by GDSimpson3** [comment] 2024-02-19 20:31
> Hi @RayCulp or @GDSimpson3 , could you do me a favor and recreate this issue here: https://github.com/ubports/ubports.com/issues Now it is raised against "docs.ubports.com" but that's not where the issue is and so it's more cumbersome to get attention from the right people. I tried to transfer it just now, but I couldn't figure out how to do it, so maybe it's easiest if you could recreate it?

Oh sorry, i completely forgot about this, I somehow didn't get notified about these comments, i am sure the issue must be resolved by now but will check, Thanks @doniks and @RayCulp.
