### ISSUE TITLE
Update Android apps Page

### ISSUE THREAD

**Issue by d0n601** [ubports/docs.ubports.com#305] opened 2020-05-04 18:48 UTC
The [page](http://docs.ubports.com/en/latest/userguide/dailyuse/anbox.html) regarding the installation of Android apps breaks the Wifi functionality on the Nexus 5.

It really should be noted somewhere that unless you're on the development branch, not the stable branch, this will happen. Additional, when on the development branch, there is no need to flash the `anbox-boot-hammerhead.img` image via fastboot anymore. The only required steps are the second portion of installing it via `apt` as copied below.

```
adb shell # connect from your host computer to your UT device
sudo mount -o rw,remount /
sudo apt update
sudo apt install anbox-ubuntu-touch android-tools-adb
anbox-tool install
exit
```

See  issue [#1264](https://github.com/ubports/ubuntu-touch/issues/1264) for reference.

**Comment by doniks** [comment] 2020-05-04 19:29
Hey @d0n601 

Wrt wifi issue: this is #1264 right? It seem the issue is solved. Is it not?

Wrt kernel flashing. Have you notice this recent change? https://github.com/ubports/docs.ubports.com/pull/300/files Does this address your point?

**Comment by d0n601** [comment] 2020-05-04 19:47
The issue is solved in the development branch of UBports for the Nexus 5, but not on the stable branch. I can't say why it hasn't been merged yet, but #1264 was closed because of the dev branch solution. Perhaps just a warning on the page stating that this requires users to be on the dev branch.

I'm not sure about the wrt kernel flashing change, I don't believe that's related.

**Comment by doniks** [comment] 2020-05-04 20:02
> The issue is solved in the development branch of UBports for the Nexus 5, but not on the stable branch. I can't say why it hasn't been merged yet, but #1264 was closed because of the dev branch solution. Perhaps just a warning on the page stating that this requires users to be on the dev branch.
> 

Riiight. Weellll. So, we expect that with the next stable release the problem will go away. In that case, I would lean towards not changing the docs page. The docs page is not a bug tracker. Every day there can be bugs introduced, detected, fixed. Only in rare cases does it justify doubling the work and not only updating issues and code, but also the docs. I think the anbox page has sufficient warnings all over the place that it's an experimental feature. so ..... Well, tell you what. If you think it's important enough and you make a PR to put the warning in, and you promise to not forget and come back after the next stable and make a PR to take the warning out ... then I merge it :)




> I'm not sure about the wrt kernel flashing change, I don't believe that's related.

Please elaborate. The PR I linked introduces the statement that you only need to flash kernels with specific devices. You were stating that with some devices you don't need to flash a kernel .... what's the difference?

**Comment by d0n601** [comment] 2020-05-04 20:10
>So, we expect that with the next stable release the problem will go away. 
That would be my initial assumption as well, but it's not been implemented in the stable branch for 6 months now, but has been working via the dev branch.


> You were stating that with some devices you don't need to flash a kernel .... what's the difference?
My apologies, there is no difference. No difference I simply didn't read that closely enough.

**Comment by doniks** [comment] 2020-07-10 06:11
Soooo, I guess we are good?! Issue still needed? Closing. Correct me if I'm wrong by reopening

**Closed by doniks** 2020-07-10 06:11 UTC
